export const mobileNames = [
  { nameFa: "سامسنوگ", nameEn: "Samsung" },
  { nameFa: "شیائومی", nameEn: "Xiaomi" },
  { nameFa: "هوآوی", nameEn: "Huawei" },
  { nameFa: "اپل", nameEn: "Apple" },
  { nameFa: "نوکیا", nameEn: "Nokia" },
  { nameFa: "آنر", nameEn: "Honor" },
  { nameFa: "موتورولا", nameEn: "Motorola" },
  { nameFa: "ال جی", nameEn: "LG" },
  { nameFa: "ریلمی", nameEn: "Realme" },
  { nameFa: "وان پلاس", nameEn: "OnePlus" },
  { nameFa: "ایسوس", nameEn: "ASUS" },
  { nameFa: "اچ تی سی", nameEn: "HTC" },
  { nameFa: "سونی", nameEn: "Sony" },
  { nameFa: "جی ال ایکس", nameEn: "GLX" },
  { nameFa: "اسمارت", nameEn: "Smart" },
  { nameFa: "کاجیتل", nameEn: "KGTEL" },
  { nameFa: "هوپ", nameEn: "Hope" },
  { nameFa: "اینفینیکس", nameEn: "Infinix" },
  { nameFa: "لنوو", nameEn: "Lenovo" },
  { nameFa: "ارد", nameEn: "Orod" },
  { nameFa: "زد تی ای", nameEn: "ZTE" },
  { nameFa: "آلکاتل", nameEn: "Alcatel" },
  { nameFa: "کاترپیلار", nameEn: "CAT" },
  { nameFa: "بلو", nameEn: "Blu" },
  { nameFa: "بلک بری", nameEn: "BlackBerry" },
  { nameFa: "دوجی", nameEn: "DOOGEE" },
  { nameFa: "گوگل", nameEn: "Google" },
  { nameFa: "جی پلاس", nameEn: "GPlus" },
  { nameFa: "اوپو", nameEn: "OPPO" },
  { nameFa: "اینونس", nameEn: "Invens" },
  { nameFa: "ویفون", nameEn: "Vfone" },
  { nameFa: "فلای", nameEn: "Fly" },
  { nameFa: "دیمو", nameEn: "Dimo" },
  { nameFa: "ادسن", nameEn: "Odscn" },
  { nameFa: "تکنو", nameEn: "Techno" },
  { nameFa: "ویوو", nameEn: "Wiwu" },
  { nameFa: "مالتی فون", nameEn: "MultiPhone" },
  { nameFa: "ونوس", nameEn: "Venus" },
  { nameFa: "میزو", nameEn: "Meizu" },
  { nameFa: "مایکروسافت", nameEn: "Microsoft" },
  { nameFa: "داکس", nameEn: "DOX" },
  { nameFa: "لیگو", nameEn: "Leagoo" },
  { nameFa: "کنکورد پلاس", nameEn: "Concord Plus" },
  { nameFa: "هیوندای", nameEn: "Hyundai" },
  { nameFa: "مارشال", nameEn: "Marshal" },
  { nameFa: "الفون", nameEn: "ELEPHONE" },
  { nameFa: "هات ویو", nameEn: "HOTWAV" },
  { nameFa: "ورتو", nameEn: "Verto" },
  { nameFa: "انرجایزر", nameEn: "Energizer" },
  { nameFa: "لاوا", nameEn: "LAVA" },
];
